### ISSUE TITLE
com.semmle.util.exception.CatastrophicError: Program depends on template extensional defectResults, but no value was supplied for it

### ISSUE THREAD

**Issue by imanoracle** [Semmle/ql#2395]
Hello,

I can run a single rule without any problem by using Codeql CLI, but when I pass the Java rule folder, I get the following error. Could you please help me to solve the problem?

```
Starting evaluation of codeql-java/Security/CWE/CWE-129/ImproperValidationOfArrayConstruction.ql.
Starting evaluation of codeql-java/Security/CWE/CWE-129/ImproperValidationOfArrayIndex.ql.
Starting evaluation of codeql-java/Security/CWE/CWE-129/ImproperValidationOfArrayConstructionCodeSpecified.ql.
Starting evaluation of codeql-java/Security/CWE/CWE-129/ImproperValidationOfArrayConstructionLocal.ql.
Starting evaluation of codeql-java/Security/CWE/CWE-078/ExecTainted.ql.
Starting evaluation of codeql-java/Security/CWE/CWE-078/ExecRelative.ql.
Starting evaluation of codeql-java/Security/CWE/CWE-078/ExecUnescaped.ql.
Starting evaluation of codeql-java/Security/CWE/CWE-078/ExecTaintedLocal.ql.
Oops! A fatal internal error occurred.
com.semmle.util.exception.CatastrophicError: Program depends on template extensional defectResults, but no value was supplied for it
	at com.semmle.inmemory.caching.TemplateStore.<init>(TemplateStore.java:34)
	at com.semmle.inmemory.MemoryBackend.executeQuery(MemoryBackend.java:291)
	at com.semmle.cli2.ql.EvaluationCommon.lambda$executeQueryAsync$2(EvaluationCommon.java:149)
	at com.semmle.util.concurrent.FutureUtils.futureAutoclose(FutureUtils.java:182)
	at com.semmle.cli2.ql.EvaluationCommon.executeQueryAsync(EvaluationCommon.java:147)
	at com.semmle.cli2.execute.ExecuteQueriesCommand.lambda$executeSubcommand$2(ExecuteQueriesCommand.java:199)
	at com.semmle.cli2.ql.Paralleliser$1.lambda$next$0(Paralleliser.java:68)
	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:214)
	at com.semmle.cli2.ql.Paralleliser.lambda$startMoreJobs$1(Paralleliser.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by hmakholm** [comment]
This is a known problem: Some of the `.ql` files in the public CodeQL repository do not actually define queries one can apply to a codebase. They belong to a now-discontinued (but still in use by some legacy customers) product and need to run in a special environment that the new CLI doesn't support. Unfortunately they'll still be picked up when you just name the entire directory on the `codeql` command line, and attempting to execute them produces the error you see.

We're looking into ways to make the user experience of this smoother.

For now, the recommended way to run all of the meaningful queries is not to give the _directory_ as a command-line argument, but instead point to the _query suite_ `.../java/ql/src/codeql-suites/java-lgtm-full.qls`. (Or you might want to first try just `java-lgtm.qls` which excludes queries that are hidden by default on LGTM.com due to having too many false positives).

**Comment by imanoracle** [comment]
Thank you
