### ISSUE TITLE
General issue Database error

### ISSUE THREAD

**Issue by butterflyhack** [Semmle/ql#2472]
**Description of the issue**

I use codeql create a new database from a new source project, the project is ubuntu source project. create database is successful, when I run codeql script to query, the database will occur a Internal error.  the output log is below:
```
adlab@ubuntu:~/codeqlhome/ql/cpp/ql/src$ /home/adlab/codeqlhome/codeql/codeql query run test.ql -d /home/adlab/Downloads/linux-5.3.0/ubuntutest/
Compiling query plan for /home/adlab/codeqlhome/ql/cpp/ql/src/test.ql.
WARNING: Unused variable source (/home/adlab/codeqlhome/ql/cpp/ql/src/test.ql:25,40-46)
WARNING: Unused variable sink (/home/adlab/codeqlhome/ql/cpp/ql/src/test.ql:25,63-67)
[1/1] Compiled /home/adlab/codeqlhome/ql/cpp/ql/src/test.ql (817ms).
Starting evaluation of codeql-cpp/test.ql.
Oops! A fatal internal error occurred.
com.semmle.util.exception.CatastrophicError: An error occurred during the evaluation of Element::Element::getEnclosingElement_dispred#ff_10#join_rhs/2
The predicate was:
SYNTHETIC Element::Element::getEnclosingElement_dispred#ff_10#join_rhs(int arg0, int arg1) :- 
    {2} r1 = SCAN Element::Element::getEnclosingElement_dispred#ff@staged_ext AS I OUTPUT I.<1>, I.<0>
    return r1

The RA to evaluate was:
    {2} r1 = SCAN Element::Element::getEnclosingElement_dispred#ff@staged_ext AS I OUTPUT I.<1>, I.<0>
    return r1

(eventual cause: UserError "Severe disk cache trouble (corruption or out of space) at /home/adlab/Downloads/...")
	at com.semmle.inmemory.eval.Evaluate.reportError(Evaluate.java:405)
	at com.semmle.inmemory.eval.Evaluate.evaluate(Evaluate.java:149)
	at com.semmle.inmemory.relations.ProgramEvaluator.evaluateIntensionalWithDependecies(ProgramEvaluator.java:397)
	at com.semmle.inmemory.relations.ProgramEvaluator.lambda$null$15(ProgramEvaluator.java:662)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: Severe disk cache trouble (corruption or out of space) at /home/adlab/Downloads/linux-5.3.0/ubuntutest/db-cpp/default/cache/pages/87.pack: Directory entry with negative distance: next offset is 1391+0
	at com.semmle.inmemory.caching.RelationCacheImpl.lambda$create$0(RelationCacheImpl.java:82)
	at com.semmle.inmemory.caching.byhash.disk.DirectoryFile.errorWhileParsing(DirectoryFile.java:261)
	at com.semmle.inmemory.caching.byhash.disk.DirectoryFile.errorWhileParsing(DirectoryFile.java:257)
	at com.semmle.inmemory.caching.byhash.disk.DirectoryFile.hasNext(DirectoryFile.java:164)
	at com.semmle.inmemory.caching.byhash.disk.OnDiskPack$Scanner.doScan(OnDiskPack.java:658)
	at com.semmle.inmemory.caching.byhash.disk.OnDiskPack.<init>(OnDiskPack.java:559)
	at com.semmle.inmemory.caching.byhash.disk.OnDiskStore$PackPointer.ensureIsRead(OnDiskStore.java:521)
	at com.semmle.inmemory.caching.byhash.disk.OnDiskStore.getEntry(OnDiskStore.java:271)
	at com.semmle.inmemory.caching.byhash.disk.OnDiskStore.getItem(OnDiskStore.java:171)
	at com.semmle.inmemory.caching.byhash.evict.CacheChainPartialMetadata.getItem(CacheChainPartialMetadata.java:69)
	at com.semmle.inmemory.caching.byhash.interfaces.HashBasedCache.getItem(HashBasedCache.java:49)
	at com.semmle.inmemory.caching.RelationCacheImpl.getPage(RelationCacheImpl.java:277)
	at com.semmle.inmemory.caching.PagedRelation.getPage(PagedRelation.java:109)
	at com.semmle.inmemory.caching.PagedRelation.map(PagedRelation.java:160)
	at com.semmle.inmemory.pipeline.AbstractRelationPipeline.runInternal(AbstractRelationPipeline.java:28)
	at com.semmle.inmemory.pipeline.Pipeline.run(Pipeline.java:108)
	at com.semmle.inmemory.pipeline.TupleOperationPipeline.runInternal(TupleOperationPipeline.java:25)
	at com.semmle.inmemory.pipeline.Pipeline.run(Pipeline.java:108)
	at com.semmle.inmemory.eval.Evaluate.evaluate(Evaluate.java:147)
	... 7 more
```
I think the error because of the space of disk.  the space of disk :
```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.6G     0  3.6G   0% /dev
tmpfs           794M  1.8M  792M   1% /run
/dev/sda1        99G   34G   61G  36% /
```
I raise the space of disk to 100G, the error is same, so now  I dont know how to solve the error.

**Comment by hmakholm** [comment]
@butterflyhack, since you are not in fact out of disk space, we can ignore the `out of space` suggestion in the exception message. It is there mostly to mean, "this is one of several symptoms that we have seen happen to people who actually fill up their disk completely, so you should investigate whether that is your situation".

If your problem persists even after clearing the cache with `codeql database cleanup --mode=brutal`, you may have hit a bug in the evaluator. Would you be at liberty to share the database it happens with, so we can attempt to reproduce it at our end?

**Comment by hmakholm** [comment]
Closing this due to inactivity and lack of reproduction.
