### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by RichardWarburton** [Semmle/ql#2572]
**Description of the false positive**

`blockPosition` is re-assigned in the parent class where it's defined: `BlockablePosition`. So this test can fail.

https://lgtm.com/projects/g/real-logic/artio/snapshot/2ce37d3a611344d491f7b85209d925c55ee05850/files/artio-core/src/main/java/uk/co/real_logic/artio/engine/framer/SlowPeeker.java?sort=name&dir=ASC&mode=heatmap#xad28fbdb70844b02:1

**Comment by aschackmull** [comment]
Trying to understand how that would happen, I guess that would require one of the calls to either `peekImage.position()`, `normalImage.position()`, `peekImage.controlledPeek(..)`, or `peekImage.isClosed()` to down the line call `BlockablePosition.blockPosition(..)` on the same instance of the `SlowPeeker` object, right? The analysis tries to account for this possibility but fails to find a possible call-chain of this kind as the methods on `io.aeron.Image` aren't included in the database.  Also, since `io.aeron.Image` presumably (I'm guessing, I might be wrong) doesn't know about the `BlockablePosition`, I wouldn't expect such a call-chain?  If such a call-chain doesn't happen then the value assigned in line 34 should reach the test in line 45 as the analysis concludes.

**Comment by RichardWarburton** [comment]
Yeah - I appreciate it's quite a complex scenario to analyze:

`peekImage.controlledPeek` takes a handler as an argument - this is a callback whose `onFragment` method gets called by the Aeron library when a message is received and it's that that updates the `blockPosition`. There are two different implementations of handler that get passed in. Let's focus on one of them in this issue.

If you look at `Framer.sendOutboundMessages` then the `librarySlowPeek` is called with `Framer.senderEndPointAssembler` as an argument. That is initialized in the constructor of `Framer` with an `io.aeron.ControlledFragmentAssembler` whose `onFragment` method delegates to `SenderEndPoints.onFragment` which calls `SenderEndPoints.onSlowConsumerMessageFragment` which eventually calls `SenderEndPoint.onSlowOutboundMessage` which calls `SenderEndPoint.attemptSlowMessage` which calls `SenderEndPoint.blockPosition` which calls `BlockablePosition.blockPosition` where the value is set.

Just to demonstrate this I've added a line to print a stacktrace on my desktop and re-run our test suite, here's an example stack trace.

```
    java.lang.Exception
        at uk.co.real_logic.artio.dictionary.generation.Exceptions.printStackTrace(Exceptions.java:100)
        at uk.co.real_logic.artio.engine.framer.BlockablePosition.blockPosition(BlockablePosition.java:19)
        at uk.co.real_logic.artio.engine.framer.SenderEndPoint.blockPosition(SenderEndPoint.java:397)
        at uk.co.real_logic.artio.engine.framer.SenderEndPoint.attemptSlowMessage(SenderEndPoint.java:370)
        at uk.co.real_logic.artio.engine.framer.SenderEndPoint.onSlowOutboundMessage(SenderEndPoint.java:299)
        at uk.co.real_logic.artio.engine.framer.SenderEndPoints.onSlowConsumerMessageFragment(SenderEndPoints.java:159)
        at uk.co.real_logic.artio.engine.framer.SenderEndPoints.onFragment(SenderEndPoints.java:136)
        at io.aeron.ControlledFragmentAssembler.onFragment(ControlledFragmentAssembler.java:122)
        at io.aeron.Image.controlledPeek(Image.java:629)
        at uk.co.real_logic.artio.engine.framer.SlowPeeker.peek(SlowPeeker.java:38)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker$LibrarySlowPeeker.peek(SubscriptionSlowPeeker.java:100)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker.peek(SubscriptionSlowPeeker.java:43)
        at uk.co.real_logic.artio.engine.framer.Framer.sendOutboundMessages(Framer.java:372)
        at uk.co.real_logic.artio.engine.framer.Framer.doWork(Framer.java:322)
```

Hopefully that should clarify why it's a false positive.

**Comment by aschackmull** [comment]
Ok, thanks, I see what's happening now.  This is no easy fix, but I do have some ideas.  Currently we don't analyze bytecode, so we can't see what's going on in `io.aeron.Image`, but this is something that we are looking to add support for.  When this happens I think we should be able to expand the call-chain detection to identify this case and remove the FP.  So in summary, this is not something that we'll be able to fix short-term.  In the meantime you may want to make use of comment-based alert-suppression (you can add the comment `lgtm[java/constant-comparison]` to the end of line 45, cf. https://lgtm.com/help/lgtm/alert-suppression).
