### ISSUE TITLE
Database creation fails on Zulip

### ISSUE THREAD

**Issue by gbleaney** [Semmle/ql#2974]
I have a clean clone of the [Zulip Open Source project](https://github.com/zulip/zulip), and I'm trying to build a new database. I checked out a fresh copy of `codeql-cli` and got myself set up according to [these instructions](https://help.semmle.com/codeql/codeql-cli/procedures/get-started.html), and ran the following command:
```
~/codeql-home/codeql-cli/codeql database create test_codeql_db --language=python
```

It failed with the following output:
```
[2020-03-03 15:00:49] [build] [INFO] [12] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/Carbon/Dialogs.py in 156ms
[2020-03-03 15:00:49] [build] [INFO] [12] Extracted module _Qd in 3ms
[2020-03-03 15:00:49] [build] [INFO] [4] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py in 8683ms
[2020-03-03 15:00:49] [build] [INFO] [10] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/Carbon/Events.py in 194ms
[2020-03-03 15:00:49] [build] [ERROR] [10] Failed to extract module Nav: Navigation Services not available in 64-bit mode
[2020-03-03 15:00:49] [build] [INFO] [7] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/sysconfig.py in 1029ms
[2020-03-03 15:00:49] [build] [INFO] [3] Extracted file /Users/gbleaney/zulip_clean/tools/lib/gitlint-rules.py in 352ms
[2020-03-03 15:00:49] [build] [INFO] [7] Extracted module _Ctl in 21ms
[2020-03-03 15:00:49] [build] [INFO] [11] Extracted file /Users/gbleaney/zulip_clean/zerver/lib/soft_deactivation.py in 805ms
[2020-03-03 15:00:49] [build] [INFO] [7] Extracted file /Users/gbleaney/zulip_clean/zerver/migrations/0146_userprofile_message_content_in_email_notifications.py in 30ms
[2020-03-03 15:00:49] [build] [INFO] [7] Extracted file /Users/gbleaney/zulip_clean/zerver/webhooks/yo/__init__.py in 7ms
[2020-03-03 15:00:49] [build] [TRACEBACK] [10] "semmle/worker.py", line 234, in _extract_loop
[2020-03-03 15:00:49] [build] [TRACEBACK] [10] "semmle/extractors/super_extractor.py", line 50, in process
[2020-03-03 15:00:49] [build] [TRACEBACK] [10] "semmle/extractors/builtin_extractor.py", line 15, in process
[2020-03-03 15:00:49] [build] [INFO] [10] Extracted file /Users/gbleaney/zulip_clean/zerver/migrations/0185_realm_plan_type.py in 31ms
[2020-03-03 15:00:49] [build] [INFO] [11] Extracted file /Users/gbleaney/zulip_clean/zerver/tornado/application.py in 78ms
[2020-03-03 15:00:49] [build] [INFO] [3] Extracted file /Users/gbleaney/zulip_clean/zerver/migrations/0145_reactions_realm_emoji_name_to_id.py in 140ms
[2020-03-03 15:00:49] [build] [INFO] [9] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py in 3314ms
[2020-03-03 15:00:49] [build] [INFO] [1] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py in 572ms
[2020-03-03 15:00:50] [build] [INFO] [8] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/applesingle.py in 456ms
[2020-03-03 15:00:50] [build] [INFO] [4] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/macostools.py in 338ms
[2020-03-03 15:00:50] [build] [INFO] [12] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py in 512ms
[2020-03-03 15:00:50] [build] [INFO] [7] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/feedparser.py in 667ms
[2020-03-03 15:00:50] [build] [INFO] [6] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/rfc822.py in 2387ms
[2020-03-03 15:00:51] [build] [INFO] [5] Extracted file /opt/homebrew/Cellar/python27/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py in 3001ms
[2020-03-03 15:00:51] [build] [ERROR] Process 2 timed out
[2020-03-03 15:00:52] [build-err] Traceback (most recent call last):
[2020-03-03 15:00:52] [build-err]   File "/Users/gbleaney/codeql-home/codeql-cli/python/tools/index.py", line 17, in <module>
[2020-03-03 15:00:52] [build-err]     buildtools.index.main()
[2020-03-03 15:00:52] [build-err]   File "/home/jenkins/slave/workspace/CodeQL-CLI/job/git/target/thirdparty/python/build/extractor-python/buildtools/index.py", line 115, in main
[2020-03-03 15:00:52] [build-err]     
[2020-03-03 15:00:52] [build-err]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
[2020-03-03 15:00:52] [build-err]     raise CalledProcessError(retcode, cmd)
[2020-03-03 15:00:52] [build-err] subprocess.CalledProcessError: Command '['python2', '-S', '/Users/gbleaney/codeql-home/codeql-cli/python/tools/python_tracer.py', '-v', '-z', 'all', '-c', '/Users/gbleaney/zulip_clean/test_codeql_db/working/trap_cache', '-p', '/Users/gbleaney/zulip_clean/test_codeql_db/working/venv/lib', '-R', '/Users/gbleaney/zulip_clean']' returned non-zero exit status 1
[2020-03-03 15:00:52] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/Users/gbleaney/codeql-home/codeql-cli/python/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command [/Users/gbleaney/codeql-home/codeql-cli/python/tools/autobuild.sh]
```

It looks like the first error before failure was `Failed to extract module Nav: Navigation Services not available in 64-bit mode`. I'm a little stuck on what the root of this problem, because I'm assuming that Semmle is expected to work on 64-bit systems. **How can I debug this further or work past the error?**

**Comment by RasmusWL** [comment]
Hi @gbleaney, thanks for the report and sorry for taking so long to respond.

The main problem is the analysis was running as Python 2, but the project requires Python 3. For now, as a workaround you can run `export LGTM_PYTHON_SETUP_VERSION=3` in your shell before running the `codeql` command, and it should just work.

---

P.S. Before finding the core of your problem, I found some info about the error message you posted:

It seems like you are using an old version of Python 2.7, the specific error message was introduced for Python 2.7.0 [here](https://github.com/python/cpython/commit/e50a9fdd2a823296b54111b2e2080a7e4f46e9dc#diff-6741d020dbb9633fb7f04fcaeb6a6ee7R939). But the whole Mac.c file was removed in Python 2.7.4 [here](https://github.com/python/cpython/commit/69a07fbd9b2c1e2d203532d4babbc6d874d389ee).

**Comment by gbleaney** [comment]
@RasmusWL thanks for the tip! It worked to get me past that error, however, now processing just hangs forever. When I kill the process, I get this traceback:
```
[2020-03-12 12:05:06] [build-err]   File "/Users/gbleaney/codeql-home/codeql-cli/python/tools/index.py", line 17, in <module>
[2020-03-12 12:05:06] [build-err]     buildtools.index.main()
[2020-03-12 12:05:06] [build-err]   File "/home/jenkins/slave/workspace/CodeQL-CLI/job/git/target/thirdparty/python/build/extractor-python/buildtools/index.py", line 115, in main
[2020-03-12 12:05:06] [build] [INFO] Keyboard interrupt
[2020-03-12 12:05:06] [build-err]     
[2020-03-12 12:05:06] [build-err]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
[2020-03-12 12:05:06] [build-err]     retcode = call(*popenargs, **kwargs)
[2020-03-12 12:05:06] [build-err]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
[2020-03-12 12:05:06] [build-err]     return Popen(*popenargs, **kwargs).wait()
[2020-03-12 12:05:06] [build-err]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
[2020-03-12 12:05:06] [build-err]     pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
[2020-03-12 12:05:06] [build-err]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
[2020-03-12 12:05:06] [build-err]     return func(*args)
[2020-03-12 12:05:06] [build-err] KeyboardInterrupt
```
Way back in my scroll buffer I see these messages, which I'm not sure are related:
```
[2020-03-12 11:21:18] [build-err] objc[80370]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
[2020-03-12 11:21:18] [build-err] objc[80370]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by RasmusWL** [comment]
@gbleaney can you attach the entire log output? (preferably as a gist)

I understand you're working on a mac, what version of the os are you using, and what version of python are you using? (`python --version`)

**Comment by gbleaney** [comment]
Here's the full output:
https://gist.github.com/gbleaney/2022230d4d8ecce8f7fdf40d76e05758

As for version:
```
gbleaney-mbp:zulip_clean gbleaney$ python --version
Python 2.7.10
```

**Comment by RasmusWL** [comment]
@gbleaney thanks! I'll look more into this tomorrow.

What version of OSX are you using?

**Comment by RasmusWL** [comment]
Also, I don't see any error in the gist you posted. How long have you waited before interrupting the process? and could try to wait, say, 5 minutes, and post the full log after interrupting (Ctrl-C) it?

**Comment by gbleaney** [comment]
> What version of OSX are you using?

I'm on macOS Mojave Version 10.14.6 (18G103). 

> Also, I don't see any error in the gist you posted.

There are some errors hidden in the middle of the output, perhaps unrelated:
https://gist.github.com/gbleaney/2022230d4d8ecce8f7fdf40d76e05758#file-gistfile1-txt-L1354-L1355

There are no other errors, it just hangs for forever. For some reason, when I killed it while `tee`ing to output, I didn't get the traceback I saw the first time. Probably something to do with `tee`.

> How long have you waited before interrupting the process?

The first time I left it running in the background for ~30 minutes, but the log output hung after 1-2 minutes.

**Comment by RasmusWL** [comment]
Cool, thanks for proving all the extra info. I think you are right in pointing out these two lines (I was in a bit of a hurry last night, and didn't have time to look at it properly).

I fear this might be an internal problem with our tooling not working properly on OSX. We're currently investigating. I'll let you know once we have an update on this :grimacing:

**Comment by RasmusWL** [comment]
We've made a fix internally that works for Python 3 on OSX, so hopefully we'll be able to get that to you early next week (but don't want to make any promises).

Again, thanks for your patience and support :+1:

**Comment by RasmusWL** [comment]
Hi @gbleaney. We've made a new release that should fix this problem. Can you try out [version 2.0.6](https://github.com/github/codeql-cli-binaries/releases/tag/v2.0.6)? :blush:

**Comment by gbleaney** [comment]
@RasmusWL I just did a run with the latest version, and I managed to generate a database. Thanks for all the support!

**Comment by RasmusWL** [comment]
Awesome! If you haven't seen it already, check out https://securitylab.github.com/get-involved
